xpack.security.enabled: true
xpack.security.enrollment.enabled: true
xpack.security.http.ssl:
    enabled: true
    key: C:\path\to\your\key.pem
    certificate: C:\path\to\your\crt.pem
cluster.initial_master_nodes: ["elk"]
http.host: [_local_, _site_]
