xpack.security.enabled: true
xpack.security.enrollment.enabled: true
xpack.security.http.ssl:
    enabled: true
    key: ' + $ELKPath + '\elasticsearch\config\certs\' + $DNS + '-key.pem
    certificate: ' + $ELKPath + '\elasticsearch\config\certs\' + $DNS + '-crt.pem
cluster.initial_master_nodes: ["elk"]
http.host: [_local_, _site_]
